import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('1.12.43.152', username='evanhan', password='Hanrui0402')
stdin, stdout, stderr = ssh.exec_command('cat ~/fisco/chain_relay_v2.py')
print("--- SCRIPT ---")
print(stdout.read().decode())
stdin, stdout, stderr = ssh.exec_command('tail -n 20 ~/fisco/relay.log')
print("--- LOG ---")
print(stdout.read().decode())
ssh.close()
